/* Copyright (c) 2017-2022, Hans Erik Thrane */

#include <gtest/gtest.h>

#include "roq/core/json/parser.h"

#include "roq/okex/json/account.h"

using namespace roq;
using namespace roq::okex;

using namespace std::literals;
using namespace std::chrono_literals;

TEST(json_account, simple) {
  auto message = R"({)"
                 R"("adjEq":"",)"
                 R"("details":[{)"
                 R"("availBal":"",)"
                 R"("availEq":"0.0071475",)"
                 R"("cashBal":"0.0071475",)"
                 R"("ccy":"BTC",)"
                 R"("coinUsdPrice":"47869.2",)"
                 R"("crossLiab":"",)"
                 R"("disEq":"342.145107",)"
                 R"("eq":"0.0071475",)"
                 R"("eqUsd":"342.145107",)"
                 R"("frozenBal":"0",)"
                 R"("interest":"",)"
                 R"("isoEq":"0",)"
                 R"("isoLiab":"",)"
                 R"("isoUpl":"0",)"
                 R"("liab":"",)"
                 R"("maxLoan":"",)"
                 R"("mgnRatio":"",)"
                 R"("notionalLever":"0",)"
                 R"("ordFrozen":"0",)"
                 R"("stgyEq":"0",)"
                 R"("twap":"0",)"
                 R"("uTime":"1639047799870",)"
                 R"("upl":"0")"
                 R"(},{)"
                 R"("availBal":"",)"
                 R"("availEq":"0.00005916",)"
                 R"("cashBal":"0.00005916",)"
                 R"("ccy":"EOS",)"
                 R"("coinUsdPrice":"3.3287",)"
                 R"("crossLiab":"",)"
                 R"("disEq":"0.0001870795974",)"
                 R"("eq":"0.00005916",)"
                 R"("eqUsd":"0.000196925892",)"
                 R"("frozenBal":"0",)"
                 R"("interest":"",)"
                 R"("isoEq":"0",)"
                 R"("isoLiab":"",)"
                 R"("isoUpl":"0",)"
                 R"("liab":"",)"
                 R"("maxLoan":"",)"
                 R"("mgnRatio":"",)"
                 R"("notionalLever":"0",)"
                 R"("ordFrozen":"0",)"
                 R"("stgyEq":"0",)"
                 R"("twap":"0",)"
                 R"("uTime":"1624937815179",)"
                 R"("upl":"0")"
                 R"(},{)"
                 R"("availBal":"",)"
                 R"("availEq":"0.00000635",)"
                 R"("cashBal":"0.00000635",)"
                 R"("ccy":"OMG",)"
                 R"("coinUsdPrice":"5.9389",)"
                 R"("crossLiab":"",)"
                 R"("disEq":"0.000030169612",)"
                 R"("eq":"0.00000635",)"
                 R"("eqUsd":"0.000037712015",)"
                 R"("frozenBal":"0",)"
                 R"("interest":"",)"
                 R"("isoEq":"0",)"
                 R"("isoLiab":"",)"
                 R"("isoUpl":"0",)"
                 R"("liab":"",)"
                 R"("maxLoan":"",)"
                 R"("mgnRatio":"",)"
                 R"("notionalLever":"0",)"
                 R"("ordFrozen":"0",)"
                 R"("stgyEq":"0",)"
                 R"("twap":"0",)"
                 R"("uTime":"1624937815126",)"
                 R"("upl":"0")"
                 R"(})"
                 R"(],)"
                 R"("imr":"",)"
                 R"("isoEq":"0",)"
                 R"("mgnRatio":"",)"
                 R"("mmr":"",)"
                 R"("notionalUsd":"",)"
                 R"("ordFroz":"",)"
                 R"("totalEq":"342.145341637907",)"
                 R"("uTime":"1640058897449")"
                 R"(})";
  core::Buffer buffer(8192);
  core::json::Buffer buffer_(buffer);
  auto obj = core::json::Parser::create<json::Account>(message, buffer_);
}
