/* Copyright (c) 2017-2026, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/okx/protocol/json/instruments_ack.hpp"

using namespace roq;
using namespace roq::okx;

using namespace std::literals;
using namespace std::chrono_literals;

using namespace Catch::literals;

using value_type = protocol::json::InstrumentsAck;

// note! truncated
TEST_CASE("simple", "[json_instruments_ack]") {
  auto message = R"({)"
                 R"("code":"0",)"
                 R"("data":[{)"
                 R"("alias":"",)"
                 R"("auctionEndTime":"",)"
                 R"("baseCcy":"USDT",)"
                 R"("category":"1",)"
                 R"("contTdSwTime":"",)"
                 R"("ctMult":"",)"
                 R"("ctType":"",)"
                 R"("ctVal":"",)"
                 R"("ctValCcy":"",)"
                 R"("expTime":"",)"
                 R"("futureSettlement":false,)"
                 R"("groupId":"10",)"
                 R"("instFamily":"",)"
                 R"("instId":"USDT-SGD",)"
                 R"("instIdCode":189535,)"
                 R"("instType":"SPOT",)"
                 R"("lever":"",)"
                 R"("listTime":"1734678000000",)"
                 R"("lotSz":"0.001",)"
                 R"("maxIcebergSz":"999999999999999.0000000000000000",)"
                 R"("maxLmtAmt":"20000000",)"
                 R"("maxLmtSz":"999999999999999",)"
                 R"("maxMktAmt":"71000",)"
                 R"("maxMktSz":"1000000",)"
                 R"("maxPlatOILmt":"",)"
                 R"("maxStopSz":"1000000",)"
                 R"("maxTriggerSz":"999999999999999.0000000000000000",)"
                 R"("maxTwapSz":"999999999999999.0000000000000000",)"
                 R"("minSz":"1",)"
                 R"("openType":"fix_price",)"
                 R"("optType":"",)"
                 R"("posLmtAmt":"",)"
                 R"("posLmtPct":"",)"
                 R"("preMktSwTime":"",)"
                 R"("quoteCcy":"SGD",)"
                 R"("ruleType":"normal",)"
                 R"("settleCcy":"",)"
                 R"("state":"live",)"
                 R"("stk":"",)"
                 R"("tickSz":"0.0001",)"
                 R"("tradeQuoteCcyList":["SGD"],)"
                 R"("uly":"",)"
                 R"("upcChg":[])"
                 R"(},{)"
                 R"("alias":"",)"
                 R"("auctionEndTime":"",)"
                 R"("baseCcy":"USDC",)"
                 R"("category":"1",)"
                 R"("contTdSwTime":"",)"
                 R"("ctMult":"",)"
                 R"("ctType":"",)"
                 R"("ctVal":"",)"
                 R"("ctValCcy":"",)"
                 R"("expTime":"",)"
                 R"("futureSettlement":false,)"
                 R"("groupId":"10",)"
                 R"("instFamily":"",)"
                 R"("instId":"USDC-SGD",)"
                 R"("instIdCode":189536,)"
                 R"("instType":"SPOT",)"
                 R"("lever":"",)"
                 R"("listTime":"1734678600000",)"
                 R"("lotSz":"0.001",)"
                 R"("maxIcebergSz":"999999999999999.0000000000000000",)"
                 R"("maxLmtAmt":"20000000",)"
                 R"("maxLmtSz":"999999999999999",)"
                 R"("maxMktAmt":"39000",)"
                 R"("maxMktSz":"1000000",)"
                 R"("maxPlatOILmt":"",)"
                 R"("maxStopSz":"1000000",)"
                 R"("maxTriggerSz":"999999999999999.0000000000000000",)"
                 R"("maxTwapSz":"999999999999999.0000000000000000",)"
                 R"("minSz":"1",)"
                 R"("openType":"fix_price",)"
                 R"("optType":"",)"
                 R"("posLmtAmt":"",)"
                 R"("posLmtPct":"",)"
                 R"("preMktSwTime":"",)"
                 R"("quoteCcy":"SGD",)"
                 R"("ruleType":"normal",)"
                 R"("settleCcy":"",)"
                 R"("state":"live",)"
                 R"("stk":"",)"
                 R"("tickSz":"0.0001",)"
                 R"("tradeQuoteCcyList":["SGD"],)"
                 R"("uly":"",)"
                 R"("upcChg":[])"
                 R"(},{)"
                 R"("alias":"",)"
                 R"("auctionEndTime":"1733905800000",)"
                 R"("baseCcy":"OKSOL",)"
                 R"("category":"1",)"
                 R"("contTdSwTime":"1733905800000",)"
                 R"("ctMult":"",)"
                 R"("ctType":"",)"
                 R"("ctVal":"",)"
                 R"("ctValCcy":"",)"
                 R"("expTime":"",)"
                 R"("futureSettlement":false,)"
                 R"("groupId":"13",)"
                 R"("instFamily":"",)"
                 R"("instId":"OKSOL-SOL",)"
                 R"("instIdCode":188027,)"
                 R"("instType":"SPOT",)"
                 R"("lever":"",)"
                 R"("listTime":"1733902200000",)"
                 R"("lotSz":"0.000001",)"
                 R"("maxIcebergSz":"999999999999.0000000000000000",)"
                 R"("maxLmtAmt":"20000000",)"
                 R"("maxLmtSz":"999999999999",)"
                 R"("maxMktAmt":"1000000",)"
                 R"("maxMktSz":"1000000",)"
                 R"("maxPlatOILmt":"",)"
                 R"("maxStopSz":"1000000",)"
                 R"("maxTriggerSz":"999999999999.0000000000000000",)"
                 R"("maxTwapSz":"999999999999.0000000000000000",)"
                 R"("minSz":"0.001",)"
                 R"("openType":"call_auction",)"
                 R"("optType":"",)"
                 R"("posLmtAmt":"",)"
                 R"("posLmtPct":"",)"
                 R"("preMktSwTime":"",)"
                 R"("quoteCcy":"SOL",)"
                 R"("ruleType":"normal",)"
                 R"("settleCcy":"",)"
                 R"("state":"live",)"
                 R"("stk":"",)"
                 R"("tickSz":"0.0001",)"
                 R"("tradeQuoteCcyList":["SOL"],)"
                 R"("uly":"",)"
                 R"("upcChg":[])"
                 R"(},{)"
                 R"("alias":"",)"
                 R"("auctionEndTime":"1765274400000",)"
                 R"("baseCcy":"NIGHT",)"
                 R"("category":"1",)"
                 R"("contTdSwTime":"1765274400000",)"
                 R"("ctMult":"",)"
                 R"("ctType":"",)"
                 R"("ctVal":"",)"
                 R"("ctValCcy":"",)"
                 R"("expTime":"",)"
                 R"("futureSettlement":false,)"
                 R"("groupId":"13",)"
                 R"("instFamily":"",)"
                 R"("instId":"NIGHT-USDT",)"
                 R"("instIdCode":239496,)"
                 R"("instType":"SPOT",)"
                 R"("lever":"",)"
                 R"("listTime":"1765270800000",)"
                 R"("lotSz":"0.1",)"
                 R"("maxIcebergSz":"",)"
                 R"("maxLmtAmt":"20000000",)"
                 R"("maxLmtSz":"9999999999999999",)"
                 R"("maxMktAmt":"1000000",)"
                 R"("maxMktSz":"1000000",)"
                 R"("maxPlatOILmt":"",)"
                 R"("maxStopSz":"1000000",)"
                 R"("maxTriggerSz":"",)"
                 R"("maxTwapSz":"",)"
                 R"("minSz":"100",)"
                 R"("openType":"call_auction",)"
                 R"("optType":"",)"
                 R"("posLmtAmt":"",)"
                 R"("posLmtPct":"",)"
                 R"("preMktSwTime":"",)"
                 R"("quoteCcy":"USDT",)"
                 R"("ruleType":"normal",)"
                 R"("settleCcy":"",)"
                 R"("state":"preopen",)"
                 R"("stk":"",)"
                 R"("tickSz":"0.000001",)"
                 R"("tradeQuoteCcyList":["USDT"],)"
                 R"("uly":"",)"
                 R"("upcChg":[])"
                 R"(},{)"
                 R"("alias":"",)"
                 R"("auctionEndTime":"",)"
                 R"("baseCcy":"",)"
                 R"("category":"1",)"
                 R"("contTdSwTime":"",)"
                 R"("ctMult":"",)"
                 R"("ctType":"",)"
                 R"("ctVal":"",)"
                 R"("ctValCcy":"",)"
                 R"("expTime":"",)"
                 R"("futureSettlement":false,)"
                 R"("instFamily":"",)"
                 R"("instId":"NIGHT-USD",)"
                 R"("instIdCode":null,)"
                 R"("instType":"SPOT",)"
                 R"("lever":"",)"
                 R"("listTime":"1765278000000",)"
                 R"("lotSz":"",)"
                 R"("maxIcebergSz":"",)"
                 R"("maxLmtAmt":"",)"
                 R"("maxLmtSz":"",)"
                 R"("maxMktAmt":"",)"
                 R"("maxMktSz":"",)"
                 R"("maxStopSz":"",)"
                 R"("maxTriggerSz":"",)"
                 R"("maxTwapSz":"",)"
                 R"("minSz":"",)"
                 R"("openType":"",)"
                 R"("optType":"",)"
                 R"("preMktSwTime":"",)"
                 R"("quoteCcy":"",)"
                 R"("ruleType":"",)"
                 R"("settleCcy":"",)"
                 R"("state":"preopen",)"
                 R"("stk":"",)"
                 R"("tickSz":"",)"
                 R"("uly":"",)"
                 R"("upcChg":[])"
                 R"(})"
                 R"(],)"
                 R"("msg":"")"
                 R"(})";
  auto helper = [&](value_type &obj) {
    CHECK(obj.code == 0);
    CHECK(std::empty(obj.msg));
    REQUIRE(std::size(obj.data) == 5);
  };
  core::json::BufferStack buffers{8192, 2};
  value_type obj{message, buffers};
  helper(obj);
}
