{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set number = environ.get('GIT_DESCRIBE_NUMBER', 0) %}

package:
  name: roq-okex
  version: {{ version }}

source:
  path: ..

build:
  skip: True  # [win and osx]
  number: {{ number }}
  run_exports:
    - {{ pin_subpackage('roq-okex', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - roq-api =={{ version }}
    - roq-core =={{ version }}
    - roq-server =={{ version }}
    - roq-oss-crossguid
    - roq-oss-date
    - roq-oss-http-parser
    - roq-oss-benchmark

about:
  home: https://roq-trading.com
  doc_url: https://roq-trading.com/docs
  dev_url: https://github.com/roq-trading
  license: Commercial
  license_family: PROPRIETARY
  license_file: LICENSE
  summary: Roq OKEx Gateway
